#!/bin/bash
cd ebin/

gnome-terminal -x erl -sname nodeA -setcookie clave -run peer start
gnome-terminal -x erl -sname nodeB -setcookie clave -run peer start
gnome-terminal -x erl -sname nodeC -setcookie clave -run peer start
gnome-terminal -x erl -sname nodeD -setcookie clave -run initEscenario start



